4134693 18
libEGL warning: MESA-LOADER: failed to open nouveau: /usr/lib64/dri/nouveau_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri)

libEGL warning: MESA-LOADER: failed to open nouveau: /usr/lib64/dri/nouveau_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib64/dri)

Traceback (most recent call last):
  File "/home/fvs660/cleanrl/cleanrl/ppo_causal.py", line 15, in <module>
    from shimmy.registration import DM_CONTROL_SUITE_ENVS
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/shimmy/__init__.py", line 11, in <module>
    register_gymnasium_envs()
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/shimmy/registration.py", line 180, in register_gymnasium_envs
    _register_dm_control_envs()
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/shimmy/registration.py", line 60, in _register_dm_control_envs
    from shimmy.dm_control_compatibility import DmControlCompatibilityV0
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/shimmy/dm_control_compatibility.py", line 16, in <module>
    from dm_control import composer
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/composer/__init__.py", line 18, in <module>
    from dm_control.composer.arena import Arena
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/composer/arena.py", line 20, in <module>
    from dm_control import mjcf
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/mjcf/__init__.py", line 18, in <module>
    from dm_control.mjcf.attribute import Asset
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/mjcf/attribute.py", line 28, in <module>
    from dm_control.mujoco.wrapper import util
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/mujoco/__init__.py", line 18, in <module>
    from dm_control.mujoco.engine import action_spec
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/mujoco/engine.py", line 41, in <module>
    from dm_control import _render
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/_render/__init__.py", line 86, in <module>
    Renderer = import_func()
               ^^^^^^^^^^^^^
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/_render/__init__.py", line 36, in _import_egl
    from dm_control._render.pyopengl.egl_renderer import EGLContext
  File "/var/scratch/fvs660/anaconda3/lib/python3.11/site-packages/dm_control/_render/pyopengl/egl_renderer.py", line 75, in <module>
    raise ImportError('Cannot initialize a headless EGL display.')
ImportError: Cannot initialize a headless EGL display.
